apiVersion: v1
kind: Service
metadata:
  name: cruise-control-metrics
  namespace: kafka-upgrade
spec:
  ports:
  - name: metrics
    port: 9094
    targetPort: 9094
    protocol: TCP
  selector:
    strimzi.io/name: my-cluster-cruise-control
  type: ClusterIP
