apiVersion: v1
kind: ConfigMap
metadata:
  name: cruise-control-metrics-config
  namespace: kafka-upgrade
data:
  metrics-config.yml: |
    lowercaseOutputName: true
    rules:
    - pattern: "kafka.cruisecontrol<name=(.+)><>(.*)"
      name: "kafka_cruisecontrol_$1_$2"
    - pattern: "kafka.cruisecontrol<name=(.+)>"
      name: "kafka_cruisecontrol_$1"
    - pattern: "cruisecontrol<name=(.+)><>(.*)"
      name: "cruisecontrol_$1_$2"
    - pattern: "cruisecontrol<name=(.+)>"
      name: "cruisecontrol_$1"
    - pattern: "kafka.server<type=(.+), name=(.+)><>(Count|Value)"
      name: "kafka_server_$1_$2"
    - pattern: "kafka.server<type=(.+), name=(.+)><>([0-9]+.percentile)"
      name: "kafka_server_$1_$2_$3"
    - pattern: "kafka.server<type=(.+), name=(.+), clientId=(.+)><>(Count|Value)"
      name: "kafka_server_$1_$2_$3"
    - pattern: ".*"
