apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-metrics-config
  namespace: kafka-upgrade
data:
  kafka-metrics-config.yml: |
    lowercaseOutputName: true
    rules:
    - pattern: "kafka.server<type=(.+), name=(.+)><>Value"
      name: "kafka_server_$1_$2"
    - pattern: "kafka.server<type=(.+), name=(.+)><>Count"
      name: "kafka_server_$1_$2_count"
    - pattern: ".*"
