apiVersion: v1
kind: ConfigMap
metadata:
  name: cruise-control-metrics-config
  namespace: kafka-upgrade
data:
  metrics-config.yml: |
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    
    rules:
      # ====================
      # CRUISE CONTROL CORE METRICS
      # ====================
      
      # Executor metrics
      - pattern: kafka.cruisecontrol<name=Executor.(.+)><>(Value|Count|Mean|Max|Min|StdDev|50thPercentile|75thPercentile|95thPercentile|98thPercentile|99thPercentile|999thPercentile)
        name: kafka_cruisecontrol_executor_$1_$2
        type: GAUGE
      
      # Analyzer metrics
      - pattern: kafka.cruisecontrol<name=Analyzer.(.+)><>(Value|Count|Mean|Max|Min|OneMinuteRate|FiveMinuteRate|FifteenMinuteRate|MeanRate)
        name: kafka_cruisecontrol_analyzer_$1_$2
        type: GAUGE
      
      # Anomaly detector metrics
      - pattern: kafka.cruisecontrol<name=AnomalyDetector.(.+)><>(Value|Count|Mean|Max|Min|OneMinuteRate|FiveMinuteRate|FifteenMinuteRate)
        name: kafka_cruisecontrol_anomalydetector_$1_$2
        type: GAUGE
      
      # Load monitor metrics
      - pattern: kafka.cruisecontrol<name=LoadMonitor.(.+)><>(Value|Count|Mean|Max|Min|OneMinuteRate|FiveMinuteRate|FifteenMinuteRate|MeanRate)
        name: kafka_cruisecontrol_loadmonitor_$1_$2
        type: GAUGE
      
      # Metric sampler metrics
      - pattern: kafka.cruisecontrol<name=MetricSampler.(.+)><>(Value|Count|Mean|Max|Min|OneMinuteRate|FiveMinuteRate|FifteenMinuteRate|MeanRate)
        name: kafka_cruisecontrol_metricsampler_$1_$2
        type: GAUGE
      
      # Goal optimizer metrics
      - pattern: kafka.cruisecontrol<name=GoalOptimizer.(.+)><>(Value|Count|Mean|Max|Min)
        name: kafka_cruisecontrol_goaloptimizer_$1_$2
        type: GAUGE
      
      # Partition metrics
      - pattern: kafka.cruisecontrol<name=Partition.(.+)><>(Value|Count)
        name: kafka_cruisecontrol_partition_$1_$2
        type: GAUGE
      
      # Broker metrics
      - pattern: kafka.cruisecontrol<name=Broker.(.+)><>(Value|Count|Mean|Max|Min)
        name: kafka_cruisecontrol_broker_$1_$2
        type: GAUGE
      
      # ====================
      # CRUISE CONTROL SENSORS
      # ====================
      
      - pattern: kafka.cruisecontrol<name=([^.]+)\.([^.]+)\.([^.]+)><>(Value|Count|Mean|Max|Min|OneMinuteRate|FiveMinuteRate|FifteenMinuteRate|MeanRate)
        name: kafka_cruisecontrol_$1_$2_$3_$4
        type: GAUGE
      
      # ====================
      # CRUISE CONTROL GENERIC PATTERNS
      # ====================
      
      # Two-level hierarchy
      - pattern: kafka.cruisecontrol<name=([^.]+)\.(.+)><>(Value|Count|Mean|Max|Min|OneMinuteRate|FiveMinuteRate|FifteenMinuteRate|MeanRate|50thPercentile|75thPercentile|95thPercentile|98thPercentile|99thPercentile|999thPercentile)
        name: kafka_cruisecontrol_$1_$2_$3
        type: GAUGE
      
      # Single-level metrics
      - pattern: kafka.cruisecontrol<name=(.+)><>(Value|Count|Mean|Max|Min|OneMinuteRate|FiveMinuteRate|FifteenMinuteRate|MeanRate)
        name: kafka_cruisecontrol_$1_$2
        type: GAUGE
      
      # Metrics without attributes
      - pattern: kafka.cruisecontrol<name=(.+)><>(.+)
        name: kafka_cruisecontrol_$1_$2
        type: GAUGE
      
      # ====================
      # CRUISE CONTROL (without kafka prefix)
      # ====================
      
      - pattern: com.linkedin.cruisecontrol<name=([^.]+)\.(.+)><>(Value|Count|Mean|Max|Min|OneMinuteRate|FiveMinuteRate|FifteenMinuteRate|MeanRate)
        name: cruisecontrol_$1_$2_$3
        type: GAUGE
      
      - pattern: com.linkedin.cruisecontrol<name=(.+)><>(Value|Count|Mean|Max|Min)
        name: cruisecontrol_$1_$2
        type: GAUGE
      
      - pattern: com.linkedin.cruisecontrol<name=(.+)><>(.+)
        name: cruisecontrol_$1_$2
        type: GAUGE
      
      # ====================
      # CRUISE CONTROL STATE METRICS
      # ====================
      
      - pattern: kafka.cruisecontrol<type=KafkaCruiseControlState, name=(.+)><>(Value)
        name: kafka_cruisecontrol_state_$1_$2
        type: GAUGE
      
      # ====================
      # CRUISE CONTROL ASYNC OPERATIONS
      # ====================
      
      - pattern: kafka.cruisecontrol<type=async-(.+), name=(.+)><>(Value|Count|Mean|Max|Min|OneMinuteRate)
        name: kafka_cruisecontrol_async_$1_$2_$3
        type: GAUGE
      
      # ====================
      # USER TASK MANAGER
      # ====================
      
      - pattern: kafka.cruisecontrol<name=UserTaskManager.(.+)><>(Value|Count|Mean|Max|Min)
        name: kafka_cruisecontrol_usertaskmanager_$1_$2
        type: GAUGE
      
      # ====================
      # KAFKA METRICS (for Cruise Control's Kafka clients)
      # ====================
      
      # Producer metrics
      - pattern: kafka.producer<type=producer-metrics, client-id=(.+)><>(.+)
        name: kafka_producer_metrics_$2
        type: GAUGE
        labels:
          client_id: "$1"
      
      - pattern: kafka.producer<type=producer-topic-metrics, client-id=(.+), topic=(.+)><>(.+)
        name: kafka_producer_topic_metrics_$3
        type: GAUGE
        labels:
          client_id: "$1"
          topic: "$2"
      
      # Consumer metrics
      - pattern: kafka.consumer<type=consumer-metrics, client-id=(.+)><>(.+)
        name: kafka_consumer_metrics_$2
        type: GAUGE
        labels:
          client_id: "$1"
      
      - pattern: kafka.consumer<type=consumer-fetch-manager-metrics, client-id=(.+), topic=(.+)><>(.+)
        name: kafka_consumer_fetch_manager_metrics_$3
        type: GAUGE
        labels:
          client_id: "$1"
          topic: "$2"
      
      - pattern: kafka.consumer<type=consumer-fetch-manager-metrics, client-id=(.+)><>(.+)
        name: kafka_consumer_fetch_manager_metrics_$2
        type: GAUGE
        labels:
          client_id: "$1"
      
      # Admin client metrics
      - pattern: kafka.admin.client<type=admin-client-metrics, client-id=(.+)><>(.+)
        name: kafka_admin_client_metrics_$2
        type: GAUGE
        labels:
          client_id: "$1"
      
      # ====================
      # JVM METRICS (for Cruise Control process)
      # ====================
      
      # Memory
      - pattern: java.lang<type=Memory><HeapMemoryUsage>(.+)
        name: jvm_memory_heap_$1
        type: GAUGE
      
      - pattern: java.lang<type=Memory><NonHeapMemoryUsage>(.+)
        name: jvm_memory_nonheap_$1
        type: GAUGE
      
      # Memory pool
      - pattern: java.lang<type=MemoryPool, name=(.+)><Usage>(.+)
        name: jvm_memory_pool_$2
        type: GAUGE
        labels:
          pool: "$1"
      
      # Garbage collector
      - pattern: java.lang<type=GarbageCollector, name=(.+)><>CollectionCount
        name: jvm_gc_collection_count
        type: COUNTER
        labels:
          gc: "$1"
      
      - pattern: java.lang<type=GarbageCollector, name=(.+)><>CollectionTime
        name: jvm_gc_collection_time_ms
        type: COUNTER
        labels:
          gc: "$1"
      
      # Threading
      - pattern: java.lang<type=Threading><>(ThreadCount|DaemonThreadCount|PeakThreadCount|TotalStartedThreadCount)
        name: jvm_threads_$1
        type: GAUGE
      
      # ClassLoading
      - pattern: java.lang<type=ClassLoading><>(LoadedClassCount|TotalLoadedClassCount|UnloadedClassCount)
        name: jvm_classes_$1
        type: GAUGE
      
      # Runtime
      - pattern: java.lang<type=Runtime><>(Uptime|StartTime)
        name: jvm_runtime_$1
        type: GAUGE
      
      # Operating System
      - pattern: java.lang<type=OperatingSystem><>(ProcessCpuLoad|SystemCpuLoad|ProcessCpuTime|AvailableProcessors|FreePhysicalMemorySize|TotalPhysicalMemorySize|FreeSwapSpaceSize|TotalSwapSpaceSize|CommittedVirtualMemorySize|OpenFileDescriptorCount|MaxFileDescriptorCount)
        name: jvm_os_$1
        type: GAUGE
      
      # ====================
      # CATCH-ALL FOR ANY REMAINING CRUISE CONTROL METRICS
      # ====================
      
      # Uncomment to capture everything (WARNING: high cardinality)
      # - pattern: kafka.cruisecontrol<(.+)><>(.+)
      #   name: kafka_cruisecontrol_catchall
      #   type: GAUGE
      #   labels:
      #     mbean: "$1"
      #     attribute: "$2"
