apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingress-nginx-leader-election
  namespace: ingress-nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-nginx-leader-election
subjects:
- kind: ServiceAccount
  name: ingress-nginx
  namespace: ingress-nginx
