apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kafka-upgrade
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      # Cruise Control metrics
      - job_name: 'cruise-control'
        static_configs:
        - targets: ['cruise-control-metrics:9404']
        scrape_interval: 30s
        metrics_path: '/metrics'

      # Kafka broker process metrics (CPU + Memory only)
      #- job_name: 'kafka-brokers-process'
      #  kubernetes_sd_configs:
       # - role: pod
        #  namespaces:
         #   names:
          #    - kafka-upgrade
        #relabel_configs:
        #- source_labels: [__meta_kubernetes_pod_label_strimzi_io_name]
         # action: keep
         # regex: my-cluster-kafka
        #- source_labels: [__meta_kubernetes_pod_container_port_number]
         # action: keep
          #regex: 9404
        #- source_labels: [__meta_kubernetes_pod_ip]
         # target_label: __address__
          #replacement: $1:9404
        #metric_relabel_configs:
        #- source_labels: [__name__]
         # regex: "process_cpu_seconds_total|process_resident_memory_bytes"
          #action: keep

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: kafka-upgrade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/
        - name: prometheus-data
          mountPath: /prometheus
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
      - name: prometheus-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: kafka-upgrade
spec:
  selector:
    app: prometheus
  ports:
  - name: web
    port: 9090
    targetPort: 9090
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: kafka-upgrade
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: kafka-upgrade
